### ISSUE TITLE
Remove Uses of numpy.matrix

### ISSUE THREAD

**Issue by JHartzer** [suneeshjacob/ACRoD#4] opened 2023-10-10 03:03 UTC
From [numpy](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html#numpy-matrix): "It is no longer recommended to use `numpy.matrix`, even for linear algebra. Instead use regular arrays. The class may be removed in the future." 

With this depreciation warning in mind, it would be good to remove usage of the matrix class and replace the uses with `numpy.array`.

**Comment by suneeshjacob** [comment] 2023-10-22 21:44
Replaced matrix object of NumPy to array object in all occurrences of functions.py file, and the tests are successful. Hence the issue is resolved and i am closing the issue. Thanks.

**Closed by suneeshjacob** 2023-10-22 21:44 UTC
